export const PACKAGES = [
  {
    id: 'trial',
    name: '3-Day Free Trial',
    tierKey: 'trial',
    price: '$0 Free Trial',
    badge: '3 DAYS FREE',
    cadence: 'Daily Morning (06:00 UTC)',
    records: 'Full Feed Access',
    desc: 'Test-drive daily morning extraction in your Google Sheet or webhook for 3 days. Zero upfront deposit or card required.',
  },
  {
    id: 'starter',
    name: 'Starter Docket Feed',
    tierKey: 'weekly',
    price: '$150/mo',
    cadence: 'Weekly Batch (4x / mo)',
    records: 'Up to 2,000 filings/mo',
    desc: 'Single-county municipal registries, boutique legal teams, or weekly recap pipelines.',
  },
  {
    id: 'production',
    name: 'Production Feed',
    tierKey: 'daily',
    price: '$250/mo',
    badge: 'RECOMMENDED',
    cadence: 'Daily Morning (06:00 UTC)',
    records: 'Up to 15,000 filings/mo',
    desc: 'Our flagship daily feed. Autonomous Cloudflare/WAF bypass, custom schema mapping, and self-healing AST repair.',
  },
  {
    id: 'enterprise',
    name: 'Enterprise Swarm',
    tierKey: 'enterprise',
    price: '$590/mo',
    cadence: 'Hourly / Continuous Sync',
    records: 'Unlimited filings/mo',
    desc: 'Continuous multi-county monitoring, automated PDF OCR extraction, and private proxy pools.',
  },
  {
    id: 'buyout',
    name: 'Perpetual Code Buyout',
    tierKey: 'buyout',
    price: '$1,500 One-Time',
    cadence: 'Self-Hosted Runtime',
    records: 'Unlimited & Autonomous',
    desc: 'Standalone Playwright & Python AST pipeline repository (.zip) for 100% self-hosted perpetual operation.',
  },
];
