"""Add Ticket, CancellationRequest, EmailTemplate models

Revision ID: d69d3b3ea6c8
Revises: efc25972c1b8
Create Date: 2026-08-27 19:10:55.891505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69d3b3ea6c8'
down_revision: Union[str, Sequence[str], None] = 'efc25972c1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('template_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_a', sa.String(length=500), nullable=False),
    sa.Column('subject_b', sa.String(length=500), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('variant', sa.Enum('A', 'B', name='abtestvariant'), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cancellation_requests',
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('lead_id', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REFUNDED', 'CANCELLED', name='cancellationstatus'), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('processed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_cancellation_requests_lead_id'), 'cancellation_requests', ['lead_id'], unique=False)
    op.create_table('tickets',
    sa.Column('ticket_id', sa.String(length=255), nullable=False),
    sa.Column('lead_id', sa.String(length=255), nullable=False),
    sa.Column('ticket_type', sa.Enum('SELECTOR_REPAIR', 'DELIVERY_ISSUE', 'BILLING', 'GENERAL', name='tickettype'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('sla_breached', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_tickets_lead_id'), 'tickets', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_lead_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_cancellation_requests_lead_id'), table_name='cancellation_requests')
    op.drop_table('cancellation_requests')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
