"""initial schema

Revision ID: efc25972c1b8
Revises: 
Create Date: 2026-08-27 15:27:31.289457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc25972c1b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('lead_id', sa.String(length=255), nullable=False),
    sa.Column('tier_key', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('selected_fields', sa.Text(), nullable=False),
    sa.Column('qa_score', sa.Float(), nullable=True),
    sa.Column('preview_rows', sa.Integer(), nullable=False),
    sa.Column('deposit_paid', sa.Integer(), nullable=False),
    sa.Column('final_paid', sa.Integer(), nullable=False),
    sa.Column('subscription_active', sa.Integer(), nullable=False),
    sa.Column('buyout_paid', sa.Integer(), nullable=False),
    sa.Column('audit_log', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('outreach_subject', sa.Text(), nullable=False),
    sa.Column('outreach_body', sa.Text(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('webhook_idempotency',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('sandboxes',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('lead_id', sa.String(length=255), nullable=False),
    sa.Column('rows', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('progress', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sandboxes')
    op.drop_table('webhook_idempotency')
    op.drop_table('leads')
    # ### end Alembic commands ###
