"""Catalog of high-yield B2B public record verticals, portals, and query blueprints."""

from typing import Any

VERTICAL_CATALOG: dict[str, dict[str, Any]] = {
    "Commercial Construction & Regional Building Permits": {
        "dataset_key": "austin-commercial-permits",
        "portal_name": "City of Austin Issued Construction Permits",
        "target_url": "https://data.austintexas.gov/Building-and-Development/Issued-Construction-Permits/3syk-w9eu",
        "jurisdiction": "Austin, Travis County, TX",
        "niche": "Commercial Construction & General Contracting",
        "pain_point": "Needs daily feed of non-residential commercial building permits to bid subcontracting and structural trades before competitors.",
        "tier_key": "daily",
        "buyer_search_queries": [
            "top commercial general contractors Austin Texas",
            "commercial preconstruction estimating builders Austin Texas",
            "commercial construction contracting companies Travis County",
        ],
    },
    "Federal Defense RFPs, Solicitations & SAM.gov Awards": {
        "dataset_key": "sam-gov-defense-rfps",
        "portal_name": "SAM.gov Federal Contract Opportunities",
        "target_url": "https://sam.gov/content/opportunities",
        "jurisdiction": "Federal (DoD / Civilian Agencies)",
        "niche": "Defense Contracting & GovTech Solicitations",
        "pain_point": "Needs automated tracking of newly posted DoD and federal civilian RFPs and pre-solicitation notices.",
        "tier_key": "ai",
        "buyer_search_queries": [
            "commercial federal defense subcontractors proposal bidding Texas",
            "regional defense logistics and supply subcontractors",
            "mid market federal contracting firms NAICS 541512",
        ],
    },
    "Secretary of State UCC Secured Asset Financing & Commercial Debt": {
        "dataset_key": "state-ucc-filings",
        "portal_name": "Texas Secretary of State UCC Registry",
        "target_url": "https://www.sos.state.tx.us/corp/ucc.shtml",
        "jurisdiction": "State of Texas (SOS)",
        "niche": "Equipment Financing & Commercial Asset-Backed Lending",
        "pain_point": "Needs daily updates on UCC-1 financing statements to identify commercial equipment acquisitions and subordinate lien exposure.",
        "tier_key": "daily",
        "buyer_search_queries": [
            "commercial equipment finance lenders Texas",
            "commercial asset based lending equipment factoring firms",
            "commercial equipment leasing companies Austin Houston",
        ],
    },
    "State Medical Board & Healthcare Practitioner Credentialing": {
        "dataset_key": "medical-board-licensing",
        "portal_name": "Texas Medical Board Physician Registry",
        "target_url": "https://www.tmb.state.tx.us/",
        "jurisdiction": "State of Texas (TMB)",
        "niche": "Healthcare Staffing & Physician Credentialing",
        "pain_point": "Needs daily automated extracts of newly licensed physicians and disciplinary updates to recruit active practitioners.",
        "tier_key": "weekly",
        "buyer_search_queries": [
            "physician recruiting and staffing firms Texas",
            "healthcare locum tenens credentialing agencies Dallas Austin",
            "executive medical search and physician placement firms",
        ],
    },
    "County Probate Court Dockets & Estate Asset Administration": {
        "dataset_key": "cook-county-probate",
        "portal_name": "Cook County Probate Division Court Portal",
        "target_url": "https://www.cookcountyclerkofcourt.org/",
        "jurisdiction": "Cook County, IL (Chicago)",
        "niche": "Probate & High-Net-Worth Estate Administration",
        "pain_point": "Needs automated tracking of newly filed probate petitions and letters of office across Cook County courts.",
        "tier_key": "daily",
        "buyer_search_queries": [
            "probate and estate administration law firms Chicago Cook County",
            "trust and estate litigation attorneys Chicago Illinois",
            "private wealth estate fiduciary law firms Cook County",
        ],
    },
    "Trustee Foreclosure Postings, Deeds of Trust & Lis Pendens": {
        "dataset_key": "orange-foreclosure",
        "portal_name": "Orange County Comptroller & Clerk Registry",
        "target_url": "https://www.occompt.com/",
        "jurisdiction": "Orange County, FL (Orlando)",
        "niche": "Mortgage Foreclosures & Distressed Real Estate",
        "pain_point": "Needs daily lis pendens and trustee foreclosure filings across Orange County to manage legal default workflows.",
        "tier_key": "ai",
        "buyer_search_queries": [
            "mortgage default servicing law firms Orlando Florida",
            "commercial real estate foreclosure law firms Orange County Florida",
            "distressed real estate acquisition fund Orlando Florida",
        ],
    },
    "Harris County Foreclosure Postings & Commercial Real Estate Deeds": {
        "dataset_key": "harris-foreclosure",
        "portal_name": "Harris County District Clerk & County Clerk",
        "target_url": "https://www.cclerk.hctx.net/",
        "jurisdiction": "Harris County, TX (Houston)",
        "niche": "Trustee Foreclosures & Mortgage Liens",
        "pain_point": "Needs automated tracking of Harris County foreclosure recordings and trustee auction schedules.",
        "tier_key": "daily",
        "buyer_search_queries": [
            "commercial foreclosure default law firms Houston Texas",
            "trustee foreclosure mortgage servicing firms Harris County",
            "distressed commercial property investment firms Houston",
        ],
    },
    "County Property Tax Liens & Commercial Tax Delinquencies": {
        "dataset_key": "maricopa-tax-liens",
        "portal_name": "Maricopa County Treasurer & Assessor",
        "target_url": "https://treasurer.maricopa.gov/",
        "jurisdiction": "Maricopa County, AZ (Phoenix/Scottsdale)",
        "niche": "Property Tax Liens & Delinquent Real Estate",
        "pain_point": "Needs automated tracking of delinquent commercial parcel assessments and tax sale certificates.",
        "tier_key": "weekly",
        "buyer_search_queries": [
            "commercial property tax lien investment funds Phoenix Arizona",
            "tax lien certificate asset management firms Maricopa County",
            "distressed real estate tax debt acquisition Arizona",
        ],
    },
    "Fulton County Probate & High-Net-Worth Estate Intelligence": {
        "dataset_key": "fulton-probate",
        "portal_name": "Probate Court of Fulton County",
        "target_url": "https://www.fultoncountyga.gov/probatecourt",
        "jurisdiction": "Fulton County, GA (Atlanta)",
        "niche": "Probate & Estate Administration",
        "pain_point": "Needs real-time court dockets of newly filed Fulton County probate petitions and letters of administration.",
        "tier_key": "daily",
        "buyer_search_queries": [
            "probate court estate administration attorneys Atlanta Georgia",
            "trust and estate fiduciary law firms Fulton County",
            "private wealth estate litigation attorneys Atlanta",
        ],
    },
    "Texas Statewide Corporate Entities & Commercial Registry": {
        "dataset_key": "texas-open-data",
        "portal_name": "Texas Statewide Public Registry",
        "target_url": "https://data.texas.gov/",
        "jurisdiction": "State of Texas (Austin)",
        "niche": "State Entity Filings & Commercial Liens",
        "pain_point": "Needs daily feed of newly formed corporations, LLCs, and entity amendments across Texas.",
        "tier_key": "weekly",
        "buyer_search_queries": [
            "corporate filing and registered agent companies Texas",
            "entity formation and corporate compliance service firms Texas",
            "B2B corporate intelligence and commercial registry firms Austin Dallas",
        ],
    },
}
