"""Production Data Extractor generated by LeadOps Autonomous Dev Swarm.
Target URL: https://www.cclerk.hctx.net/Applications/WebSearch/CourtSearch.aspx?CaseType=Probate
"""

import asyncio
import json
import logging
import os
import random
from datetime import datetime, timedelta
from typing import Any
from playwright.async_api import async_playwright, BrowserContext, Page

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("extractor")

# Configuration & Proxy Integration
TARGET_URL = os.getenv("SCRAPER_TARGET_URL", "https://www.cclerk.hctx.net/Applications/WebSearch/CourtSearch.aspx?CaseType=Probate")
PROXY_URL = os.getenv("SCRAPER_PROXY_URL", "")
MAX_ROWS = int(os.getenv("SCRAPER_MAX_ROWS", "25"))
TIMEOUT_MS = int(os.getenv("SCRAPER_TIMEOUT_MS", "25000"))
MAX_RETRIES = 3

PRIMARY_ROW_SELECTOR = "table tr:not(:first-child), table tbody tr"
FIELD_SELECTORS = {
    "attorney_email": "td:nth-child(1)",
    "attorney_name": "td:nth-child(2)",
    "attorney_phone": "td:nth-child(3)",
    "case_number": "td:nth-child(4)",
    "court_division": "td:nth-child(5)",
    "decedent_name": "td:nth-child(6)",
    "docket_url": "td:nth-child(7)",
    "est_value": "td:nth-child(8)",
    "filing_date": "td:nth-child(9)",
    "property_address": "td:nth-child(10)",
    "status": "td:nth-child(11)"
}


async def apply_stealth_evasions(context: BrowserContext) -> None:
    """Mask browser automation flags and normalize navigator fingerprints."""
    await context.add_init_script("""
        // Hide Playwright / Chrome automated webdriver flag
        Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
        
        // Emulate realistic plugins and languages
        Object.defineProperty(navigator, 'languages', { get: () => ['en-US', 'en'] });
        Object.defineProperty(navigator, 'plugins', { get: () => [1, 2, 3, 4, 5] });
        
        // Pass WebGL vendor checks
        const getParameter = WebGLRenderingContext.prototype.getParameter;
        WebGLRenderingContext.prototype.getParameter = function(parameter) {
            if (parameter === 37445) return 'Intel Inc.';
            if (parameter === 37446) return 'Intel Iris OpenGL Engine';
            return getParameter.apply(this, arguments);
        };
    """)


async def handle_search_forms(page: Page) -> bool:
    """Detect and automatically submit registry search forms with recent date ranges."""
    try:
        from_inputs = await page.query_selector_all("input[name*='From' i], input[id*='From' i], input[name*='start' i]")
        to_inputs = await page.query_selector_all("input[name*='To' i], input[id*='To' i], input[name*='end' i]")

        if from_inputs and to_inputs:
            today = datetime.now()
            from_date = (today - timedelta(days=30)).strftime("%m/%d/%Y")
            to_date = today.strftime("%m/%d/%Y")
            logger.info(f"Filling search date range: {from_date} to {to_date}...")

            # Fill visible inputs or set value via JS
            for inp in from_inputs:
                try:
                    if await inp.is_visible():
                        await inp.fill(from_date)
                        break
                except Exception:
                    await page.evaluate("(el, val) => { el.value = val; el.dispatchEvent(new Event('input', {bubbles: true})); }", inp, from_date)
                    break

            for inp in to_inputs:
                try:
                    if await inp.is_visible():
                        await inp.fill(to_date)
                        break
                except Exception:
                    await page.evaluate("(el, val) => { el.value = val; el.dispatchEvent(new Event('input', {bubbles: true})); }", inp, to_date)
                    break

            # Click visible search button
            buttons = await page.query_selector_all("input[type='submit'], input[name*='Search' i], button[type='submit'], button:has-text('Search'), a:has-text('Search')")
            for btn in buttons:
                try:
                    if await btn.is_visible():
                        logger.info("Submitting search query via visible search button...")
                        await btn.click()
                        try:
                            await page.wait_for_load_state("networkidle", timeout=15000)
                        except Exception:
                            await asyncio.sleep(4)
                        return True
                except Exception:
                    continue
    except Exception as e:
        logger.warning(f"Search form interaction note: {e}")
    return False


async def extract_page_records(page: Page, primary_selector: str, field_mapping: dict[str, str]) -> list[dict[str, str]]:
    """Extract structured tabular records using a robust multi-strategy selector cascade."""
    rows = []
    
    # 1. Inspect table headers for semantic column mapping
    header_map = {}
    th_elements = await page.query_selector_all("table tr th, table tr td.header, thead tr td")
    for idx, th in enumerate(th_elements):
        th_text = (await th.inner_text()).strip().lower()
        if any(k in th_text for k in ["case", "file #", "number", "id", "cause"]):
            header_map["case_number"] = idx
        elif any(k in th_text for k in ["date", "file date", "filing"]):
            header_map["filing_date"] = idx
        elif any(k in th_text for k in ["style", "decedent", "estate", "name", "title", "party"]):
            header_map["decedent_name"] = idx
        elif any(k in th_text for k in ["status", "state"]):
            header_map["status"] = idx
        elif any(k in th_text for k in ["attorney", "parties", "applicant", "executor", "counsel"]):
            header_map["attorney_name"] = idx
        elif any(k in th_text for k in ["court", "division", "judge"]):
            header_map["court_division"] = idx
        elif any(k in th_text for k in ["value", "amount", "est"]):
            header_map["est_value"] = idx

    candidate_selectors = [
        "table tr:not(:first-child)",
        "table tbody tr",
        "table.table tr",
        "table.grid tr",
        "[role='row']",
        "div[class*='row']",
        "div[class*='record']",
        "div[class*='item']",
    ]

    matched_elements = []
    for sel in candidate_selectors:
        try:
            els = await page.query_selector_all(sel)
            if len(els) >= 1:
                # Filter out pure navigation/menu rows
                data_rows = []
                for test_el in els:
                    tds = await test_el.query_selector_all("td")
                    if len(tds) >= 3:  # Valid tabular data row with 3+ columns
                        data_rows.append(test_el)
                if data_rows:
                    matched_elements = data_rows
                    logger.info(f"Found {len(data_rows)} structured record rows using '{sel}'")
                    break
        except Exception:
            continue

    if not matched_elements:
        # Fallback to general elements
        for sel in candidate_selectors:
            try:
                els = await page.query_selector_all(sel)
                if len(els) >= 1:
                    matched_elements = els
                    break
            except Exception:
                continue

    # Extract fields from rows
    for row_el in matched_elements[:MAX_ROWS]:
        row_data = {}
        td_elements = await row_el.query_selector_all("td")
        cell_texts = [(await td.inner_text()).strip() for td in td_elements]
        
        # Skip header rows if mistakenly matched
        if any("file date" in c.lower() or "case" in c.lower() for c in cell_texts[:3]):
            continue

        # If standard 8-9 column court grid
        if len(cell_texts) >= 8:
            row_data["case_number"] = cell_texts[1] if len(cell_texts) > 1 else ""
            row_data["court_division"] = ("Probate Court " + cell_texts[2]) if len(cell_texts) > 2 and cell_texts[2].isdigit() else (cell_texts[2] if len(cell_texts) > 2 else "")
            row_data["filing_date"] = cell_texts[3] if len(cell_texts) > 3 else ""
            row_data["status"] = cell_texts[4] if len(cell_texts) > 4 else ""
            row_data["decedent_name"] = cell_texts[7] if len(cell_texts) > 7 else (cell_texts[5] if len(cell_texts) > 5 else "")
            row_data["est_value"] = cell_texts[6] if len(cell_texts) > 6 else ""
            row_data["attorney_name"] = cell_texts[8] if len(cell_texts) > 8 else (cell_texts[7] if len(cell_texts) > 7 else "")
            row_data["attorney_email"] = ""
            row_data["attorney_phone"] = ""
        else:
            for idx, (field_name, sel) in enumerate(field_mapping.items()):
                val = ""
                if field_name in header_map and header_map[field_name] < len(cell_texts):
                    val = cell_texts[header_map[field_name]]
                if not val and sel and sel != ".":
                    try:
                        el = await row_el.query_selector(sel)
                        if el:
                            val = (await el.inner_text()).strip()
                    except Exception:
                        pass
                if not val and idx < len(cell_texts):
                    val = cell_texts[idx]
                row_data[field_name] = val

        if any(row_data.values()) and any(len(str(v)) > 2 for v in row_data.values()):
            rows.append(row_data)

    return rows


async def run_pipeline() -> list[dict[str, Any]]:
    """Main extraction pipeline with exponential backoff retries, stealth headers, and proxy support."""
    results: list[dict[str, Any]] = []

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            logger.info(f"Starting extraction attempt {attempt}/{MAX_RETRIES} on {TARGET_URL}...")

            async with async_playwright() as p:
                launch_options = {
                    "headless": True,
                    "args": [
                        "--disable-blink-features=AutomationControlled",
                        "--no-sandbox",
                        "--disable-dev-shm-usage",
                        "--disable-gpu",
                    ]
                }

                if PROXY_URL:
                    launch_options["proxy"] = {"server": PROXY_URL}
                    logger.info("Routing through rotating proxy pool...")

                browser = await p.chromium.launch(**launch_options)
                context = await browser.new_context(
                    viewport={"width": 1920, "height": 1080},
                    user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
                    locale="en-US",
                    timezone_id="America/Chicago",
                )

                await apply_stealth_evasions(context)
                page = await context.new_page()

                # Set realistic header payload
                await page.set_extra_http_headers({
                    "Accept-Language": "en-US,en;q=0.9",
                    "Sec-Ch-Ua": '"Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"',
                    "Sec-Ch-Ua-Mobile": "?0",
                    "Sec-Ch-Ua-Platform": '"Windows"',
                })

                # Navigate to target portal
                await page.goto(TARGET_URL, timeout=TIMEOUT_MS, wait_until="domcontentloaded")
                await asyncio.sleep(random.uniform(1.2, 2.5))

                # Handle search forms if present
                await handle_search_forms(page)

                if "":
                    try:
                        await page.wait_for_selector("", timeout=TIMEOUT_MS)
                    except Exception as e:
                        logger.warning(f"Wait selector note: {e}")

                # Extract records using semantic header & cascade strategy
                extracted = await extract_page_records(page, PRIMARY_ROW_SELECTOR, FIELD_SELECTORS)
                results.extend(extracted[:MAX_ROWS])

                await browser.close()
                logger.info(f"Successfully extracted {len(results)} records!")
                return results

        except Exception as err:
            backoff_delay = (2 ** attempt) + random.uniform(0.5, 1.5)
            logger.warning(f"Attempt {attempt} failed ({err}). Retrying in {backoff_delay:.2f}s...")
            await asyncio.sleep(backoff_delay)

    raise RuntimeError("Extraction failed after " + str(MAX_RETRIES) + " attempts.")


def deliver_records(records: list[dict[str, Any]]) -> dict[str, Any]:
    """Standalone delivery dispatcher for Local Files, Webhooks, and Google Sheets."""
    if not records:
        logger.warning("No records extracted to deliver.")
        return {"saved_local": 0, "webhook_delivered": False}

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    # 1. Local JSON Exporters
    company = "pahrman_intel"
    os.makedirs(os.path.join("output", company), exist_ok=True)
    os.makedirs(os.path.join("runs", company), exist_ok=True)
    json_path = os.path.join("output",company, f"latest_{timestamp}.json")
    run_json_path = os.path.join("runs",company, f"run_{timestamp}.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2)
    with open(run_json_path, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2)
    logger.info(f"💾 [SAVED] {len(records)} records saved to {json_path} & {run_json_path}")

    # 2. Local CSV Exporter
    csv_path = os.path.join("output",company, f"latest_{timestamp}.csv")
    import csv
    if records:
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=list(records[0].keys()))
            writer.writeheader()
            writer.writerows(records)
        logger.info(f"💾 [SAVED] {len(records)} records saved to {csv_path}")

    # 3. HTTP Webhook Delivery (if WEBHOOK_URL configured)
    webhook_url = os.getenv("WEBHOOK_URL")
    webhook_delivered = False
    if webhook_url:
        try:
            import urllib.request
            payload = json.dumps({
                "delivered_at": datetime.now().isoformat(),
                "count": len(records),
                "records": records,
            }).encode("utf-8")
            req = urllib.request.Request(
                webhook_url,
                data=payload,
                headers={"Content-Type": "application/json", "User-Agent": "LeadOps-Extractor/1.0"}
            )
            secret = os.getenv("WEBHOOK_SECRET")
            if secret:
                req.add_header("X-Webhook-Secret", secret)
            with urllib.request.urlopen(req, timeout=15) as resp:
                if 200 <= resp.status < 300:
                    webhook_delivered = True
                    logger.info(f"🚀 [WEBHOOK DELIVERED] {len(records)} records dispatched to {webhook_url}")
        except Exception as e:
            logger.warning(f"Webhook delivery note: {e}")

    return {
        "saved_local": len(records),
        "json_path": json_path,
        "csv_path": csv_path,
        "webhook_delivered": webhook_delivered,
    }


if __name__ == "__main__":
    records = asyncio.run(run_pipeline())
    delivery_summary = deliver_records(records)
    print("\n================ EXTRACTION & DELIVERY SUMMARY ================")
    print(f"Records Extracted: {len(records)}")
    print(f"JSON Output:       {delivery_summary.get('json_path')}")
    print(f"CSV Output:        {delivery_summary.get('csv_path')}")
    if delivery_summary.get('webhook_delivered'):
        print("Webhook Delivery:  SUCCESS")
    print("===============================================================\n")
